### PR TITLE
Split main.rs

### PR DESCRIPTION
**Pull request by Virviil**
`main.rs` has too much business logic inside, so it's a bit hard to navigate throw the project.

Intention for this PR - make a more or less logical module and file structure for easy navigation throw the project.

Big changes:
- [x] Each subcommand should be located logically in it's own file under `actions` directory
- [x] Move all structopts structs and enums in separate file
- [x] Split utils into logical parts. Move functions aware for only one use inside `main.rs` to appropriate util
- [x] Move `pyproject.toml` parsing part in separate module

Small changes:
- [x] While `.idea` is gitignored - it's somehow appeared inside the repo. Removing
- [x] Remove `unreachable!()` macro after `abort`
- [x] Added `success` function to exit 0 after all ok

### CODE REVIEW

**Comment by Virviil** [comment]
Seems to be ready, ofc there is a lot of work, but it seems to be a logical end for the first step, and there is a lot to review

**Comment by Virviil** [comment]
@David-OConnor Can you please review? I want to continue from here. Thanks!!!!

**Comment by David-OConnor** [comment]
Solid refactor. I agree that the reorganization here makes more sense

**Comment by Virviil** [comment]
Great! Thx

**Pull request merged**
