### PR TITLE
Refactoring of code for parsing dependencies

### PR DESCRIPTION
**Pull request by higumachan**
#83

### CODE REVIEW

**Comment by David-OConnor** [comment]
At a glance, this is much better, provided it works in a similar way. I agree that regex isn't the proper tool for this. Eg all the possible failure points to check logic at contributed to parsing code being a mess.

**Comment by higumachan** [comment]
Thank you for response!

I think nom can it works in a similar way.

I think I can pass all the current tests with a nom-based implementation by next Monday at the latest.

**Comment by higumachan** [comment]
The implementation is done, and we have confirmed that all current tests have passed.
Please point out anything that's hard to read.

Thanks.

**Comment by David-OConnor** [comment]
Looks like a nice improvement over the existing Regex soup.

**Pull request merged**
