### PR TITLE
Make color output optional

### PR DESCRIPTION
**Pull request by tanj**
:heavy_minus_sign: crossterm
:heavy_plus_sign: termcolor
:heavy_plus_sign: atty

Termcolor allows for turning off colors by setting a ColorChoice. This
commit adds a commandline option to disable colors and also uses atty to
automatically determine if the output is being redirected and disable
colors in that case.

### CODE REVIEW

**Comment by tanj** [comment]
I'm going to work on this more because `fmt::Display` on `Version` is a disaster. I'm going to create a `to_string_color` function instead. Anything that uses the default `to_string` will not cause errors in version parsing.

```
Found lockfile
thread 'main' panicked at 'Problem parsing lock version: DependencyError { details: "Problem parsing version: \u{1b}[0m\u{1b}[34m0\u{1b}[0m\u{1b}[33m.\u{1b}[0m\u{1b}[34m3\u{1b}[0m\u{1b}[33m.\u{1b}[0m\u{1b}[34m1\u{1b}[0m" }', src\main.rs:703:52
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by David-OConnor** [comment]
Sounds good! Let me know when ready.

**Comment by tanj** [comment]
I'm pretty sure it's ready. We might want to build some e2e testing, but I've tested it by creating projects and adding packages to them in both Windows 10 and WSL.

**Comment by David-OConnor** [comment]
Sweet!

**Pull request merged**
